### ISSUE TITLE
Crash when switching rooms

### ISSUE THREAD

**Issue by anoadragon453** [mujx/nheko#433]
### System:

- Nheko version: 0.5.5-36c5a8f
- Installation method: AppImage
- Operating System: Debian Linux
- Desktop Environment: i3

### Debugger backtrace

```
[2018-09-06 22:17:38.724] [crypto] [critical] failed to decrypt message with index (!CnvxGeixWZvcvxdPSp:half-shot.uk, PoKKV/+nIWBGZlPHte/++jxfuhUx+X87lfYzs7POUqY, okSUdlnggVxB6TYMxS4yoDb+NEgE+0dZbcz5xEimeFE): olm_group_decrypt: UNKNOWN_MESSAGE_INDEX
[2018-09-06 22:17:38.726] [crypto] [critical] failed to decrypt message with index (!CnvxGeixWZvcvxdPSp:half-shot.uk, PoKKV/+nIWBGZlPHte/++jxfuhUx+X87lfYzs7POUqY, okSUdlnggVxB6TYMxS4yoDb+NEgE+0dZbcz5xEimeFE): olm_group_decrypt: UNKNOWN_MESSAGE_INDEX
[2018-09-06 22:17:38.728] [crypto] [critical] failed to decrypt message with index (!CnvxGeixWZvcvxdPSp:half-shot.uk, PoKKV/+nIWBGZlPHte/++jxfuhUx+X87lfYzs7POUqY, okSUdlnggVxB6TYMxS4yoDb+NEgE+0dZbcz5xEimeFE): olm_group_decrypt: UNKNOWN_MESSAGE_INDEX
[2018-09-06 22:17:38.729] [crypto] [critical] failed to decrypt message with index (!CnvxGeixWZvcvxdPSp:half-shot.uk, PoKKV/+nIWBGZlPHte/++jxfuhUx+X87lfYzs7POUqY, okSUdlnggVxB6TYMxS4yoDb+NEgE+0dZbcz5xEimeFE): olm_group_decrypt: UNKNOWN_MESSAGE_INDEX

Thread 9 "AppRun" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffec83e700 (LWP 32563)]
0x00007ffff5e4c470 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /tmp/.mount_nheko-qyV0Sx/usr/bin/../lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff5e4c470 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_nheko-qyV0Sx/usr/bin/../lib/libQt5Core.so.5
#1  0x00000000006f9622 in ImageItem::imageDownloaded (this=<optimized out>, _t1=...) at src/timeline/widgets/moc_ImageItem.cpp:159
#2  0x000000000062b856 in ImageItem::<lambda(const string&, const string&, const string&, mtx::http::RequestErr)>::operator() (err=..., 
    data="\377\330\377\340\000\020JFIF\000\001\001\001\001,\001,\000\000\377\376\000\\border bs:0 bc:#000000 ps:0 pc:#eeeeee es:0 ec:#000000 ck:500d02a4f1f1d7497340cc586896bf11\377\333\000C\000\006\004\005\006\005\004\006\006\005\006\a\a\006\b\n\020\n\n\t\t\n\024\016\017\f\020\027\024\030\030\027\024\026\026\032\035%\037\032\033#\034\026\026 , #&')*)\031\037-0-(0%()(\377\333\000C\001\a\a\a\n\b\n\023\n\n\023(\032"..., __closure=0x30a018b0) at ../src/timeline/widgets/ImageItem.cpp:52
#3  std::_Function_handler<void(const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const boost::optional<mtx::http::ClientError>&), ImageItem::downloadMedia(const QUrl&)::<lambda(const string&, const string&, const string&, mtx::http::RequestErr)> >::_M_invoke(const std::_Any_data &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const boost::optional<mtx::http::ClientError> &) (__functor=..., 
    __args#0="\377\330\377\340\000\020JFIF\000\001\001\001\001,\001,\000\000\377\376\000\\border bs:0 bc:#000000 ps:0 pc:#eeeeee es:0 ec:#000000 ck:500d02a4f1f1d7497340cc586896bf11\377\333\000C\000\006\004\005\006\005\004\006\006\005\006\a\a\006\b\n\020\n\n\t\t\n\024\016\017\f\020\027\024\030\030\027\024\026\026\032\035%\037\032\033#\034\026\026 , #&')*)\031\037-0-(0%()(\377\333\000C\001\a\a\a\n\b\n\023\n\n\023(\032"..., __args#1=..., __args#2=..., __args#3=...) at /usr/include/c++/5/functional:1871
#4  0x000000000070be27 in std::_Function_handler<void (std::string const&, boost::optional<boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::optional<mtx::http::ClientError> const&), mtx::http::Client::download(std::string const&, std::string const&, std::function<void (std::string const&, std::string const&, std::string const&, boost::optional<mtx::http::ClientError> const&)>)::{lambda(std::string const&, boost::optional<boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::optional<mtx::http::ClientError> const&)#1}>::_M_invoke(std::_Any_data const&, std::string const&, boost::optional<boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::optional<mtx::http::ClientError> const&) ()
#5  0x0000000000732a59 in std::shared_ptr<mtx::http::Session> mtx::http::Client::create_session<std::string>(std::function<void (std::string const&, boost::optional<boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::optional<mtx::http::ClientError> const&)>)::{lambda(std::string, boost::beast::http::message<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::system::error_code const&)#1}::operator()(std::string, boost::beast::http::message<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::system::error_code const&) const ()
#6  0x00000000007332e9 in std::_Function_handler<void (std::string, boost::beast::http::message<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::system::error_code const&), std::shared_ptr<mtx::http::Session> mtx::http::Client::create_session<std::string>(std::function<void (std::string const&, boost::optional<boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::optional<mtx::http::ClientError> const&)>)::{lambda(std::string, boost::beast::http::message<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::system::error_code const&)#1}>::_M_invoke(std::_Any_data const&, std::string&&, boost::beast::http::message<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::system::error_code const&) ()
#7  0x0000000000751360 in mtx::http::Session::on_request_complete() ()
#8  0x0000000000763602 in boost::beast::http::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::parser_is_done, std::_Bind<std::_Mem_fn<void (mtx::http::Session::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<mtx::http::Session>, std::_Placeholder<1>, std::_Placeholder<2>)> >::operator()(boost::system::error_code, unsigned long, bool) ()
#9  0x0000000000762f23 in boost::beast::http::detail::read_some_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::parser_is_done, std::_Bind<std::_Mem_fn<void (mtx::http::Session::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<mtx::http::Session>, std::_Placeholder<1>, std::_Placeholder<2>)> > >::operator()(boost::system::error_code, unsigned long, bool) ()
#10 0x00000000007626ae in boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffer>, boost::beast::http::detail::read_some_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::parser_is_done, std::_Bind<std::_Mem_fn<void (mtx::http::Session::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<mtx::http::Session>, std::_Placeholder<1>, std::_Placeholder<2>)> > > >::operator()(boost::system::error_code, unsigned long, int) ()
#11 0x0000000000764953 in void boost::asio::io_context::executor_type::dispatch<boost::asio::detail::binder2<boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffer>, boost::beast::http::detail::read_some_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::parser_is_done, std::_Bind<std::_Mem_fn<void (mtx::http::Session::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<mtx::http::Session>, std::_Placeholder<1>, std::_Placeholder<2>)> > > >, boost::system::error_code, unsigned long>, std::allocator<void> >(boost::asio::detail::binder2<boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffer>, boost::beast::http::detail::read_some_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::parser_is_done, std::_Bind<std::_Mem_fn<void (mtx::http::Session::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<mtx::http::Session>, std::_Placeholder<1>, std::_Placeholder<2>)> > > >, boost::system::error_code, unsigned long>&&, std::allocator<void> const&) const ()
#12 0x0000000000764ac8 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffer>, boost::beast::http::detail::read_some_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::beast::basic_flat_buffer<std::allocator<char> >, false, boost::beast::http::parser<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, std::allocator<char> >, boost::beast::http::detail::parser_is_done, std::_Bind<std::_Mem_fn<void (mtx::http::Session::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<mtx::http::Session>, std::_Placeholder<1>, std::_Placeholder<2>)> > > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
#13 0x0000000000709e98 in boost::detail::thread_data<mtx::http::Client::Client(std::string const&, unsigned short)::{lambda()#1}>::run() ()
#14 0x00007ffff79850d5 in ?? () from /tmp/.mount_nheko-qyV0Sx/usr/bin/../lib/libboost_thread.so.1.68.0
#15 0x00007ffff582ff2a in start_thread (arg=0x7fffec83e700) at pthread_create.c:463
#16 0x00007ffff5762edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Comment by unclechu** [comment]
I'm facing the same issue from time to time. Last few lines from log:
```
[2018-09-06 04:39:11.387] [ui] [info] [rdj9DBGElEbDYDsAOUQZAPIEbrbmIoV5] removed message with sync
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
Aborted (core dumped)
```
